import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const Soria = localFont({
  src: "./fonts/soria-font.ttf",
  variable: "--font-Soria",
  weight:"100-900",
});

const League = localFont({
  src:"./fonts/LeagueSpartan-VF.ttf",
  variable: "--font-League",
  weight:"100-900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Soria.variable} ${League.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
